name: build and Deploy hexo blog
on:
  push:
    branches:
      - main
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v1
        with:
          ref: master


      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          version: ${{ matrix.node_version }}


      - name: Setup hexo
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "2846154596@qq.com"
          git config --global user.name "xhlu"
          npm install hexo-cli -g --registry https://registry.npm.taobao.org
          npm install --save hexo-deployer-git --registry https://registry.npm.taobao.org

          npm install hexo-wordcount --save --registry https://registry.npm.taobao.org
          npm install hexo-generator-json-content --save  --registry https://registry.npm.taobao.org
          npm install hexo-generator-feed --save --registry https://registry.npm.taobao.org
          npm install hexo-generator-sitemap --save --registry https://registry.npm.taobao.org
          npm install hexo-generator-baidu-sitemap --save --registry https://registry.npm.taobao.org
          npm install hexo-tag-dplayer --save --registry https://registry.npm.taobao.org

          npm install
          hexo clean
          hexo g
          # hexo d

          rm -rf .git
          git clone https://github.com/luxinhua/luxinhua.github.io.git
          cd luxinhua.github.io
          git remote rm origin
          git remote add origin git@github.com:luxinhua/luxinhua.github.io.git
          git remote set-url origin git@github.com:luxinhua/luxinhua.github.io.git
          
          # rm -rf * 
          cp -rf ../public/* .
          git add .
          git commit -m "update article"
          git push origin master
